### ISSUE TITLE
[Feat] 가게 API 구현 - WEB

### ISSUE THREAD

**Issue by khwoowoo** [UMC-5th-Coumo/Coumo_Server#10]
# ⚙️ ISSUE
- 사장님(WEB) 가게 API 구현

# 📄 To-Do
- [x] 가게 비지니스 로직 구현
- [x] 가게 Rest Controller 구현
- [x] 가게 API 설명작성(Swagger)
- [x] 가게 예외처리 적용
- [x] MySQL 공간 데이터 활용
