### ISSUE TITLE
[Feat] ERD 테이블 컬럼 수정 & 도메인 수정

### ISSUE THREAD

**Issue by proysm** [UMC-5th-Coumo/Coumo_Server#21]
# ⚙️ ISSUE
**01/29 MON 중간보고 회의 후 변경사항 적용**
1. customer 테이블의 컬럼 삭제 : _닉네임_
2. owner 테이블의 컬럼 삭제 : _닉네임, 성별, 생일_
3. id 컬럼 bigint(Long)으로 자료형 변경

# 📄 To-Do
- [x] customer, owner 테이블 컬럼 삭제
- [x] 모든 id 컬럼 bigint로 수정
- [x] 따라서, 도메인은 id를 Long으로 수정
