### ISSUE TITLE
[Feat] 가게의 메뉴 수정(신메뉴 관련) - WEB

### ISSUE THREAD

**Issue by khwoowoo** [UMC-5th-Coumo/Coumo_Server#24]
# ⚙️ ISSUE
- 중간 점검 회의 때, 메뉴의 신메뉴 컬럼 추가 리팩토링

# 📄 To-Do
- [x] 도메인에 isNew 변수 추가하기
- [x] DTO, Converter, 연관 관계 편의 메소드 등등 반영하기
- [x] API 명세서 수정하기
