### ISSUE TITLE
[Feat] 👷  CI/CD 파이브라인 구축

### ISSUE THREAD

**Issue by khwoowoo** [UMC-5th-Coumo/Coumo_Server#39]
# ⚙️ ISSUE
- 프로젝트 위치 변경
- CI/CD 파이브라인 구축

# 📄 To-Do
- [ ] 프로젝트 위치 변경
- [ ] yml 파일 생성
- [ ] ELB 파일, nginx 파일, delpoly.yml, 환경변수 설정 등등
