### ISSUE TITLE
[Feat] 프로젝트 도메인 수정

### ISSUE THREAD

**Issue by junggyo1020** [UMC-5th-Coumo/Coumo_Server#7]
# ⚙️ ISSUE
- 1월 21일 회의 이후 변경된 사항을 프로젝트 도메인에 일부 수정/반영하였습니다.

# 📄 To-Do

- [ ] login_id 추가
- [ ] Timetable 테이블 추가
- [ ] working_hour 컬럼 삭제
